spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000  # maximum number of milliseconds that a client will wait for a connection
      idle-timeout: 10000  # maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      minimum-idle: 1 # minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 3 # maximum pool size
    url: jdbc:postgresql://postgres:5432/gis
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        hbm2ddl:
          delimiter: ";"
        default_schema: public
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080

transport-routing:
  routingDbHost: postgres
  routingDbPort: 5432
  routingDbUser: postgres
  routingDbPassword: postgres
  routingDbDatabase: osm
  routingDbSchema: public
  routingDbTable: gh_roads
  routingBounds:
    - - 7.258872985839843
      - 47.70410131286579
    - - 7.416629791259765
      - 47.70410131286579
    - - 7.416629791259765
      - 47.792284775391956
    - - 7.258872985839843
      - 47.792284775391956
    - - 7.258872985839843
      - 47.70410131286579
