@startuml
'https://plantuml.com/class-diagram

abstract class FeatureCollection {
  +GeoJSONFeatureCollection toGeoJSON()
  ---
  #Feature[] features
  ....
  #Feature[] getFeatures()
  #void setFeatures(Feature[])
}

abstract class Feature {
  -Geometry geometry
  -Properties properties
  ....
  #Geometry getGeometry()
  #void setGeometry(Geometry)
  #Properties getProperties()
  #void setProperties(Properties)
}

class Poi extends Feature {
  -String name
  -String address
  ....
  +String getName()
  +void setName(String)
  +String getAddress()
  +void setAddress(String)
}

class ItineraryResponse {
  -Feature<Itinerary> itineraryFeature
  -Double distance
  -Double time
  ....
  +Feature<Itinerary> getItineraryFeature()
  +void setItineraryFeature(Feature<Itinerary>)
  +Double getDistance()
  +void setDistance(Double)
  +Double getTime()
  +void setTime(Double)
}

FeatureCollection o-- Feature


@enduml
